spring:
    datasource:
        url: ${MYSQL_DATA_SOURCE}
        username: ${MYSQL_USER}
        password: ${MYSQL_PWD}

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    security:
      oauth2:
        client:
          registration:
            github:
              clientId: ${GITHUB_CLIENT_ID}
              clientSecret: ${GITHUB_CLIENT_SECRET}
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
            mercadolibre:
              clientId: ${MELI_CLIENT_ID}
              clientSecret: ${MELI_CLIENT_SECRET}
              authorizationGrantType: authorization_code
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              clientAuthenticationMethod: post
              scope: read,write,offline_access
          provider:
            mercadolibre:
              authorization-uri: https://auth.mercadolivre.com.br/authorization
              token-uri: https://api.mercadolibre.com/oauth/token
              user-info-uri: https://api.mercadolibre.com/users/me
              user-info-authentication-method: form
              user-name-attribute: nickname

app:
  auth:
    tokenSecret: ${JWT_TOKEN_SECRET}
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the frontend client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

logging:
  level: 
    root: WARN
    br.com.xrsites: TRACE
    org.springframework.security: DEBUG
